version: "3.8"

services:
  app:
    build: .
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/db
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
